#!/usr/bin/env python3
"""Generate per-effect "implementation + bytecode" pages for the docs site.

Educational asset: for each KN5000 effects-DSP effect, this pairs the MAME HLE
reconstruction (the actual C++ that renders the effect) with the DSP BYTECODE it
was reconstructed from (the disassembled microprogram). Reading the two side by
side is how we learn to read the bytecode -- and it is the bridge toward a faithful
LLE.

SOURCES (both sibling repos, never edited -- this is a pure consumer):
  * HLE code:  kn7000_mame/src/mame/matsushita/kn5000_tonegen.cpp
               Each effect is a "refresh" block (decode C-RAM params once per update)
               plus a per-sample "insert" block. They are located by the code's own
               DSPHLE flag (`const bool <flag> = (dsphle == N)` and the matching
               `if (<flag>)` inside the render loop), brace-matched out verbatim.
  * bytecode:  kn5000-roms-disasm/dsp/disasm/progNN_*.dsm  (the reverse-engineered
               microprogram, generated by gen_dsp_disasm.py).

OUTPUT: kn5000-docs/effect-impl/<name>.md, Jekyll pages at /effects-dsp/impl/<name>/,
plus an index at /effects-dsp/impl/. Deterministic / idempotent; stale pages pruned.

Run:  python3 tools/gen_effect_impl_pages.py   (or `make impl`)
Override sibling repo locations with --mame and --disasm.
"""
import argparse
import re
import subprocess
import sys
from pathlib import Path

SITE_SUBDIR = "effect-impl"
PERMALINK_BASE = "/effects-dsp/impl"
SPLIT_MARKER = "DIAGNOSTIC RENDER MODE"     # everything before = refresh; after = inserts
TONEGEN = "src/mame/matsushita/kn5000_tonegen.cpp"

# Each effect: (name, title, DSPHLE selector, refresh flag, insert flag, prog .dsm stem,
#               flowchart stem, tier, one-line grade). Shared-code combos point several
#               selectors at one flag; the page notes which branch applies.
EFFECTS = [
    # name          title                         sel    refresh_flag  insert_flag  prog_stem                  tier      grade
    ("eq",          "Parametric EQ",              0x01, "eq_hle",     "eq_hle",    "prog39_parametric_eq",    "pinned",  "5-band RBJ biquad from decoded design params (FREQ=0x03, GAIN=0x01); spectral A/B PASS."),
    ("delay",       "Single Delay",               0x02, "dly_hle",    "dly_hle",   "prog09_single_delay",     "pinned",  "feedback delay; feedback=C-RAM 0x00/0x09, length=descriptor 0x26 (350 ms); temporal A/B 350.6 ms."),
    ("chorus",      "Chorus",                     0x03, "cho_hle",    "cho_hle",   "prog01_chorus",           "pinned",  "quadrature LFO-swept delay; rate=cell 0x00 (~0.6 Hz); A/B 0.62 Hz."),
    ("flanger",     "Flanger",                    0x04, "fl_hle",     "fl_hle",    "prog04_flanger",          "pinned",  "swept delay + feedback; rate=0x05, feedback=0x00, depth=0x08."),
    ("phaser",      "Phaser",                     0x05, "ph_hle",     "ph_hle",    "prog05_phaser",           "pinned",  "swept all-pass cascade + feedback; rate=0x00, manual=0x06, depth=0x05, feedback=0x02."),
    ("ensemble",    "Ensemble",                   0x06, "ens_hle",    "ens_hle",   "prog06_ensemble",         "pinned",  "3-voice LFO-swept delay; rate=0x00, per-voice taps 0x02/0x04/0x06."),
    ("vibrato",     "Vibrato",                    0x07, "vib_hle",    "vib_hle",   "prog50_vibrato",          "pinned",  "LFO-swept pitch modulation; rate=0x02 (~4 Hz), depth=0x05."),
    ("sdelay_chorus","S.Delay + Chorus",          0x08, "cmb_sdcho",  "cmb_sdcho", "prog64_s_delay_chorus",   "pinned",  "delay (desc 0x26) chained into a chorus (rate=0x00, feedback=0x02)."),
    ("sdelay_combos","S.Delay + Flanger/Vibrato/Phaser/S.Delay", 0x09, "cmb2", "cmb2", "prog66_s_delay_flanger", "pinned", "shared combo engine: delay chained with a 2nd block (selectors 0x09-0x0c; see the branch for each)."),
    ("peq_sdelay",  "PEQ + S.Delay",              0x0d, "peqsd",      "peqsd",     "prog72_peq_s_delay",      "pinned",  "emphasis biquad (FREQ=0x03, GAIN=0x01) into a feedback delay."),
    ("reverb",      "Reverb",                     0x0e, "rv_hle",     "rv_hle",    "prog16_room_reverb_1",    "preview", "comb+all-pass tank from decoded coeffs (decay 0x97, damping 0x93, ladders 0x98/0xA1, mix 0xA9); tail 6x over dry."),
    ("distortion",  "Distortion",                 0x0f, "dist_hle",   "dist_hle",  "prog32_distortion",       "preview", "AGC waveshaper: DRIVE=0x00, VOLUME=0x02 measured; tanh clip is a labelled stand-in (class-6 table not undumped, open decode)."),
    ("enhancer",    "Enhancer",                   0x10, "enh_hle",    "enh_hle",   "prog03_enhancer",         "preview", "high-shelf emphasis + all-pass phase + decoded 350 ms slap (DELAY=0x0B proven); roles INFERRED."),
    ("exciter",     "Exciter",                    0x11, "exc_hle",    "exc_hle",   "prog35_exciter",          "preview", "high-band waveshaper (DRIVE=0x00) + tone + dry mix; adds upper harmonics. Roles INFERRED."),
    ("auto_wah",    "Auto Wah",                   0x12, "wah_hle",    "wah_hle",   "prog52_auto_wah",         "preview", "envelope-swept resonant filter (no LFO); biquad cells 0x00-0x06. Roles SPECULATIVE."),
    ("auto_pan",    "Auto Pan",                   0x13, "pan_hle",    "pan_hle",   "prog48_auto_pan",         "preview", "quadrature LFO pans L/R; rate=cell 0x01 MEASURED (~1.2 Hz)."),
    ("ring_mod",    "Ring Modulator",             0x14, "ring_hle",   "ring_hle",  "prog54_ring_modulator",   "preview", "carrier oscillator x signal; carrier rate=cell 0x00 MEASURED (~1 kHz)."),
    ("multitap",    "Multi Tap Delay",            0x15, "mtap_hle",   "mtap_hle",  "prog10_multi_tap_delay",  "preview", "4 panned taps at the MEASURED host delays 136/272/408/544 ms + feedback."),
    ("compressor",  "Compressor",                 0x16, "comp_hle",   "comp_hle",  "prog36_compressor",       "preview", "2/pi RECTIFY-and-smooth level detector (ROM 0x517CC1) -> attack/release one-pole "
     "(the ROM's own 4.712 ms / 11.764 ms) -> gain computer; the DETECTOR is decoded, "
     "the GAIN LAW is not."),
    ("gated_reverb","Gated Reverb",               0x17, "grev_hle",   "grev_hle",  "prog08_gated_reverb",     "preview", "reverb tank (MEASURED line lengths) + envelope gate chopping the tail; GATE TIME=0x15."),
    ("mixup",       "Mix Up",                     0x18, "mix_hle",    "mix_hle",   "prog56_mix_up",           "preview", "three LFOs (MEASURED 3.0/5.2/7.4 Hz = cells 0x00/0x02/0x04) modulate a short delay."),
    ("rotary",      "Rotary Speaker",             0x19, "rot_hle",    "rot_hle",   "prog15_rock_rotary",      "preview", "Leslie: crossover + two Doppler-swept (measured 7.26/3.63 ms) + AM rotors. Rotation rate not in program (canonical speeds)."),
    ("peq_combos",  "PEQ + X / Auto-Wah + Delay combos", 0x1a, "cmbx", "cmbx",     "prog71_peq_chorus",       "preview", "shared combo engine: a PEQ emphasis biquad chained with a 2nd block (selectors 0x1a-0x22; see the branch for each)."),
]


def git_slug(repo: Path) -> str:
    url = subprocess.check_output(["git", "-C", str(repo), "remote", "get-url", "origin"], text=True).strip()
    m = re.search(r"[:/]([^/:]+/[^/:]+?)(?:\.git)?$", url)
    return m.group(1) if m else "OWNER/REPO"


def strip_for_braces(line: str) -> str:
    """Blank out // comments and "..."/'...' literals so their braces don't miscount."""
    out = []
    i = 0
    while i < len(line):
        c = line[i]
        if c == '/' and i + 1 < len(line) and line[i+1] == '/':
            break
        if c in '"\'':
            q = c; i += 1
            while i < len(line):
                if line[i] == '\\':
                    i += 2; continue
                if line[i] == q:
                    i += 1; break
                i += 1
            continue
        out.append(c); i += 1
    return ''.join(out)


def block_close(lines, brace_idx):
    """Index of the line closing the { that opens at/after brace_idx (its first '{')."""
    depth = 0; started = False
    for j in range(brace_idx, len(lines)):
        s = strip_for_braces(lines[j])
        depth += s.count('{') - s.count('}')
        if '{' in s:
            started = True
        if started and depth <= 0:
            return j
    return len(lines) - 1


def extract_block(lines, start_idx):
    """Capture start_idx through the close of its first '{' (for a bare `if (...) {` block)."""
    return "\n".join(lines[start_idx:block_close(lines, start_idx) + 1])


def extract_refresh(lines, decl_idx, flag, hi):
    """Capture the declaration line, the param-var lines, AND the `if (<flag>)` block that
    follows it -- brace-matching the IF block (so { } array initializers in the param-var
    lines between decl and if do not end the capture early)."""
    if_idx = find_line(lines, rf"if \({re.escape(flag)}[\) ]", decl_idx, hi)
    if if_idx < 0:
        return "\n".join(lines[decl_idx:decl_idx + 1])
    return "\n".join(lines[decl_idx:block_close(lines, if_idx) + 1])


def read_existing_cpp(path):
    """Recover the (refresh, insert) ```cpp blocks from an already-committed page, so a rebuild
    that can no longer reach the live MAME source preserves the permanently-archived reference."""
    if not path.exists():
        return None, None
    blocks = re.findall(r"```cpp\n(.*?)\n```", path.read_text(), re.DOTALL)
    r = blocks[0].rstrip("\n") if len(blocks) >= 1 else None
    i = blocks[1].rstrip("\n") if len(blocks) >= 2 else None
    return r, i


def find_line(lines, pattern, lo=0, hi=None):
    rx = re.compile(pattern)
    hi = len(lines) if hi is None else hi
    for j in range(lo, hi):
        if rx.search(lines[j]):
            return j
    return -1


def main():
    ap = argparse.ArgumentParser()
    here = Path(__file__).resolve().parent.parent
    ap.add_argument("--mame", default=str(here.parent / "kn7000_mame"))
    ap.add_argument("--disasm", default=str(here.parent / "kn5000-roms-disasm"))
    ap.add_argument("--out", default=str(here / SITE_SUBDIR))
    args = ap.parse_args()

    mame = Path(args.mame); disasm = Path(args.disasm); outdir = Path(args.out)
    tg_path = mame / TONEGEN
    if tg_path.exists():
        tg = tg_path.read_text().split("\n")
        split = find_line(tg, re.escape(SPLIT_MARKER))
        if split < 0:
            raise SystemExit(f"split marker {SPLIT_MARKER!r} not found in {TONEGEN}")
        try:
            mame_slug = git_slug(mame)
        except Exception:
            mame_slug = "ArqueologiaDigital/MAME_Technics_Research"
    else:
        # ★ PERMANENCE: the MAME source has been removed. Do NOT fail and do NOT clobber; every
        # HLE block will fall back to the committed page archive (read_existing_cpp).
        print(f"note: {tg_path} absent -- preserving the archived HLE reference in the committed pages")
        tg = []; split = 0; mame_slug = "ArqueologiaDigital/MAME_Technics_Research"
    mame_blob = f"https://github.com/{mame_slug}/blob/main/{TONEGEN}"
    try:
        disasm_slug = git_slug(disasm)
    except Exception:
        disasm_slug = "ArqueologiaDigital/kn5000-roms-disasm"

    outdir.mkdir(parents=True, exist_ok=True)
    written = set()
    index_rows = []

    for name, title, sel, rflag, iflag, prog, tier, grade in EFFECTS:
        # refresh block: the declaration line in the refresh region, captured through its if-block
        ri = find_line(tg, rf"const (bool|int) +{re.escape(rflag)}\b", 0, split)
        refresh = extract_refresh(tg, ri, rflag, split) if ri >= 0 else "(refresh block not found)"
        # insert block: the if (<iflag>) inside the render loop (after the split marker)
        ii = find_line(tg, rf"if \({re.escape(iflag)}[\) ]", split)
        insert = extract_block(tg, ii) if ii >= 0 else "(insert block not found)"

        # ★ PERMANENCE: the HLE reference must survive removal of the MAME source. If a block
        # can no longer be extracted (source gone/renamed), PRESERVE whatever the committed page
        # already holds rather than clobbering it with a placeholder. The committed .md is the
        # permanent archive; MAME is only the import origin.
        prev_refresh, prev_insert = read_existing_cpp(outdir / f"{name}.md")
        if (not ri >= 0 or "not found" in refresh) and prev_refresh:
            refresh = prev_refresh
        if (not ii >= 0 or "not found" in insert) and prev_insert:
            insert = prev_insert

        dsm_path = disasm / "dsp" / "disasm" / f"{prog}.dsm"
        dsm = dsm_path.read_text().rstrip() if dsm_path.exists() else f"({prog}.dsm not found)"
        dsm_blob = f"https://github.com/{disasm_slug}/blob/main/dsp/disasm/{prog}.dsm"
        fc_link = "{{ site.baseurl }}" + f"/effects-dsp/flowcharts/{prog}/"

        tierlabel = ("**Intervention-pinned** (a panel control was driven and the moving C-RAM cell identified)"
                     if tier == "pinned" else
                     "**Preview** (topology decoded and reconstructed; most panel&rarr;cell role mappings are position-decoded)")
        page = f"""---
layout: page
title: "{title} — HLE + bytecode"
permalink: {PERMALINK_BASE}/{name}/
---
<!-- GENERATED by tools/gen_effect_impl_pages.py -- DO NOT EDIT; run `make impl`. -->

# {title} &mdash; HLE reconstruction and DSP bytecode

**DSPHLE selector `0x{sel:02x}`** &middot; program image `{prog}` &middot; {tierlabel}.

> {grade}

This page pairs the **bytecode** the effect runs on the NEC &micro;PD6383GF with the
**high-level reconstruction** that makes it audible in MAME. The reconstruction is not the
chip's microcode — it is a textbook DSP block built from the *decoded meaning* of that
microcode, and reading the two together is how the bytecode is understood (and, in time,
driven toward a faithful low-level emulation). See also the
[signal-flow flowchart]({fc_link}).

> **The bytecode below is the source of truth; the HLE reconstruction is not.** The HLE is our
> best current interpretation and may contain mistakes — where the two disagree, the bytecode
> wins, and a better HLE should be updated here. This page is the **permanent archive** of the
> reference HLE: it is kept here even after the code is eventually removed from the MAME sources.

## DSP bytecode (reverse-engineered microprogram)

The disassembled image the chip executes for this effect. Source (regenerable):
[`dsp/disasm/{prog}.dsm`]({dsm_blob}).

```
{dsm}
```

## HLE reconstruction (MAME, `kn5000_tonegen.cpp`)

The decode of the bytecode above, rebuilt as audible DSP. Two parts: the **parameter refresh**
(reads the decoded C-RAM coefficient cells once per update) and the **per-sample insert** (the
signal processing). Default OFF, behind the `DSPHLE` research port. Source:
[`{TONEGEN}`]({mame_blob}).

*Parameter refresh (decode the C-RAM coefficients):*

```cpp
{refresh}
```

*Per-sample insert (the reconstructed signal path):*

```cpp
{insert}
```
"""
        (outdir / f"{name}.md").write_text(page)
        written.add(f"{name}.md")
        index_rows.append((sel, name, title, tier, grade, prog))

    # index page
    rows = "\n".join(
        f"| `0x{sel:02x}` | [{title}]({{{{ site.baseurl }}}}{PERMALINK_BASE}/{name}/) | {'pinned' if t=='pinned' else 'preview'} | `{prog}` |"
        for sel, name, title, t, g, prog in sorted(index_rows)
    )
    index = f"""---
layout: page
title: "Effect HLE + bytecode"
permalink: {PERMALINK_BASE}/
---
<!-- GENERATED by tools/gen_effect_impl_pages.py -- DO NOT EDIT; run `make impl`. -->

# Effect implementations: HLE reconstruction + DSP bytecode

One page per effect, pairing the disassembled &micro;PD6383GF **microprogram** with the MAME
**HLE reconstruction** that renders it. The reconstruction is an educational bridge — it shows
what each decoded coefficient and idiom *does*, which is how the bytecode is read and, ultimately,
how a faithful low-level emulation will be built. Each effect is also drawn as a
[signal-flow flowchart]({{{{ site.baseurl }}}}/effects-dsp/flowcharts/).

| DSPHLE | Effect | Grade | Program image |
|---|---|---|---|
{rows}

*Grades:* **pinned** = a panel control was driven and the moving C-RAM cell identified;
**preview** = topology decoded and reconstructed, most panel&rarr;cell role mappings position-decoded.
Generated by `tools/gen_effect_impl_pages.py` from the live sources — see each page for links.
"""
    (outdir / "index.md").write_text(index)
    written.add("index.md")

    # prune stale
    for f in outdir.glob("*.md"):
        if f.name not in written:
            f.unlink()
    print(f"wrote {len(written)} pages to {outdir}")


if __name__ == "__main__":
    main()
